3-memes review
weazyexe/memes pull request #2
Opened 2020-04-23 17:13 UTC by weazyexe

2020-04-27 15:03 UTC, midery requested changes

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/di/NetworkModule.kt
> +        val accessToken = UserStorage(context).getAccessToken()
Лучше провайдить userStorage отдельно, в конструктор интерсептора вставлять это хранилище, и в интерсептора каждый раз доставать из него токен. Потому что иначе при логауте токен в хранилище будет очищен, а в интерсепторе - нет

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/entity/Meme.kt
> +    @PrimaryKey
Можно юзать @Parcelize из котлина, здорово упрощает работу.

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/db/MemesDao.kt
> +    fun getAll(): List<Meme>
Раз уж используется rxJava, лучше будет возвращать здесь Observable<List<Meme>> . Room поддерживает работу с rx, и оборачивает запросы к базе.

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/network/LocalRepository.kt
> +        memesDao.nukeTable()
Может быть, лучше clear?) Всё-таки это более классический вариант именования.

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/network/LocalRepository.kt
> +class LocalRepository {
Можно использовать @Inject constructor,  и перечислять параметры для инъекции в конструкторе, чтобы не приходилось явно вызвать AppComponent.inject(this), и делать все зависимости публичными.

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/entity/Meme.kt
> +@Entity
Раз уж ты решил выделить memeResponse как сущность ответа сервера, то советую выделить и MemeDb, так как он так же может отличаться от доменной сущности)

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/recycler/MemesDiffUtils.kt
> +class MemesDiffUtils(private val oldMemes: List<Meme>, private val newMemes: List<Meme>)
Круто, что решил использовать дифф утил)

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/ui/main/MainViewModel.kt
> +            .map { response -> response.map { it.convert() } }
Из networkRepository по-хорошему должны возвращаться уже доменные сущности, Memes. Так что этот map - туда)

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/ui/main/MainViewModel.kt
> +            if (memes.isEmpty()) {
Хорошая идея с хранением состояния экрана в одной переменной, мы что-то похожее имеем у себя на проектах)

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/ui/main/MainActivity.kt
> +        rootViewMain.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
А зачем здесь понадобилось на таком уровне работать с инсетами?)

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/ui/main/memes/MemesFragment.kt
> +                val diffResult = DiffUtil.calculateDiff(MemesDiffUtils(adapter.memes, memes))
Вот эту логику, наверное, лучше будет закрыть в updateMemes методе адаптера.

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/ui/main/MainViewModel.kt
> +            memes = memes.map {
Сейчас у тебя много где изменяется isFavorite мема: и на вью, и в vm, и в репозитории. Советую тебе менять его только в репозитории, и возвращать список мемов, содержащий обновлённый мем с измененным isFav. 
Таким образом, у твоего мема будет один источник правды: локальный репозиторий.

2020-04-27 15:03 UTC, midery commented on app/src/main/java/exe/weazy/memes/network/NetworkRepository.kt
>  class NetworkRepository {
Я бы советовал разделять репозитории не по дата сорсам, а по фичам: MemesRepository, AuthRepository, итд.
И не делать различий между операциями сохранения в БД / на сервер. 
В этом случае, если вдруг сервер начнет поддерживать, например, простановку лайков, тебе вообще ничего не придется менять на ui и presentation слое, а только добавить пару строк в репозиторий. А с текущим подходом тебе здорово придется менять ViewModel.

2020-04-28 12:27 UTC, weazyexe commented on app/src/main/java/exe/weazy/memes/ui/main/MainActivity.kt
> +        rootViewMain.systemUiVisibility = View.SYSTEM_UI_FLAG_LAYOUT_STABLE or
Хотелось сделать красивое отображение навбара на устройствах с андроидом 10 с навигацией жестами, edge to edge как никак)

2020-04-28 17:20 UTC, merged